# Generated by Django 5.0.3 on 2024-03-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incomes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='maount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='soutrce',
            new_name='source',
        ),
    ]
